### ISSUE TITLE
Pack OS X package on Windows host

### ISSUE THREAD

**Issue by hisune** [annexare/PackDir#6]
I tried to:

``` javascript
var Pack = require('pack-dir');
Pack.param('dmg', /osx/);
var zipPath = Pack.path(dirBuild + 'vpm.app', function(error, stdout, stderr){
    console.log(stdout);
});
```

And then I copy the vpm.app.zip to macOS, and use `unzip -xo vpm.app.zip`, then open it, it tell me I cant open this app,like that:
![image](https://cloud.githubusercontent.com/assets/7941669/15210155/9500b7f0-1867-11e6-9991-1c7981375ada.png)
(the application "vpm" cant be open)

but if I double-click on vpm.app.zip, after unzip, the application can be open.

can you tell me how to pack a zip package in win32 that can be used in macOS after unzip in command line?

**Comment by z-ax** [comment]
Didn't build for Mac from Win yet :) Thanks for the question, will check it out, but not sure if it's possible in full now. We separate builds now, but also it builds finely for Win from Mac (with Wine). Plus, DMG packaging is possible only on Mac now.

**Comment by dmythro** [comment]
Alright, it was decided to add a plugin with TAR for Windows as a DMG fallback. Then dev apps should run finely after packing.
But it will be additional NPM package to not use extra space (~1.2 MB) for it on production, where build of signed app for Mac is only possible on Mac.

Will be back on this a bit later.
